### ISSUE TITLE
Using includeReferences() strips all fields from asset except its uid

### ISSUE THREAD

**Issue by bjlarouche** [contentstack/datasync-filesystem-sdk#3]
If I use .includeReferences() on a query, then all assets in the entry returned by that query lack relevant fields such as _internal_url. For example if I had a file field named "image" all I would see for that field in the returned JSON is "image":"<UID>".

**Comment by bjlarouche** [comment]
![image](https://user-images.githubusercontent.com/13384700/62904989-5b998600-bd1d-11e9-8a30-7ce77c50d1b0.png)

**Comment by iyerrama29** [comment]
Thanks, Brandon.

We can confirm that this issue is reproducible, we'll be sure to get it fixed ASAP.

@ninadhatkar 
The following line considers assets present in the entries: https://github.com/contentstack/datasync-filesystem-sdk/blob/master/src/stack.ts#L1770
But when references aren't found in the content type: https://github.com/contentstack/datasync-filesystem-sdk/blob/master/src/stack.ts#L1685 condition changes to `true`

Action required
- Update the logic there, to run the iteration, if only assets were found


Regards,
Ramanathan K

**Comment by iyerrama29** [comment]
**A quick update**

- The above issue's patch will be part of hotfix/1.0.2 release.
- The method affected `.include()`, `.includeReferences()`

**Comment by bjlarouche** [comment]
Thanks for the update! Do you have a date for when the hotfix/1.0.2 release will be out?

**Comment by iyerrama29** [comment]
Hi @bjlarouche ,

We expect the hotfix to be live in the coming days, with the worst case scenario being next week-end.

At this point in time we've delayed the release as we'd like to better understand/debug the issue raised by you with the hotfix/1.0.2

**Comment by iyerrama29** [comment]
Closing this. The issue has been fixed in hotfix/1.0.2

@bjlarouche - can you please verify the same on your end? 

Thanks
